#!/bin/sh

# Compose a picture of the difference between given data
# and the polynomial approximation obtained with lsq(1).
# This requires gnuplot(1) to create the actual image.

err() {
	echo $@ >&2
}

fatal() {
	err $@
	exit 1
}

usage() {
	fatal "usage: $0 image lsqargs"
}

test $# -lt 2 && usage
which lsq > /dev/null || fatal lsq not found
which gnuplot > /dev/null || fatal gnuplot not found

GPLDATA=`mktemp`
trap "rm $GPLDATA" EXIT INT TERM

PICTURE=$1 ; shift
LSQDATA=$@

lsq -n -d $LSQDATA > $GPLDATA || fatal Running "'lsq 0n 0d $LSQDATA'" failed

gnuplot <<EOF
set title "lsq -n -d $LSQDATA"
set style data points
#set xrange [ "1/6/93":"1/11/93" ]
#set xrange [ "201301010000": ]
set terminal ${PICTURE##*.} medium size 1280,960
set output '$PICTURE'
set key outside
unset grid
plot	'$GPLDATA' using 1:3 with points title 'orig',	\
	''         using 1:2 with points title 'lsq',	\
	''         using 1:4 with points title 'err'
EOF
