#!/bin/sh

# Compose a picture of the difference between given data
# and the polynomial approximation obtained with lsq(1).
# This requires gnuplot(1) to create the actual image.

err() {
	echo $@ >&2
}

fatal() {
	err $@
	exit 1
}

usage() {
	fatal "usage: $0 image lsqargs"
}

test $# -lt 2 && usage
which lsq > /dev/null || fatal lsq not found
which gnuplot > /dev/null || fatal gnuplot not found

GPLDATA=`mktemp`
trap "rm $GPLDATA" EXIT INT TERM

PICTURE=$1 ; shift
PICBASE=${PICTURE%.*}
PICTYPE=${PICTURE##*.}
LSQDATA=$@

lsq -n -d $LSQDATA > $GPLDATA || fatal Running "'lsq -n -d $LSQDATA'" failed

gnuplot <<EOF
set title "lsq -n -d $LSQDATA"
set terminal $PICTYPE medium size 1280,960
set output '$PICTURE'
plot '$GPLDATA' using 1:3 pt 7 ps 0.4 title 'orig', \
     ''         using 1:2 pt 7 ps 0.4 title 'lsq'
EOF

gnuplot <<EOF
set title "errors of lsq -n -d $LSQDATA"
set terminal $PICTYPE medium size 1280,960
set output '${PICBASE}err.$PICTYPE'
plot '$GPLDATA' using 1:4 pt 7 ps 0.4 title ''
EOF
